### ISSUE TITLE
Make input text opaque

### ISSUE THREAD

**Issue by jsonmaur** [timberio/react-query-assist#10]
So it doesn't get out of alignment

**Comment by jsonmaur** [comment]
Fixed via https://github.com/timberio/react-query-assist/commit/d229c113bfd3195fc3cdf3fd581d564aaa1df87e.

Had to get a little hacky using `-webkit-text-fill-color`, but it gets the job done for everything except IE. Also if the input ever gets out of alignment with the overlay, you won't get the weird double text but the caret will still be out of place.

**Comment by zsherman** [comment]
glad that worked 👍
