### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by jsonmaur** [timberio/react-query-assist#3]
Currently no tests are in place other than linting. A few different test cases that would be good to have:

- The token regex detects all tokens in a query
- The dropdown opens at the correct times
- Filtering is working correctly while typing
- The correct enumerations are shown with an active attribute
- Only valid tokens from the attribute data are highlighted
- Selecting an autocomplete value inserts it correctly, both at end of query and in the middle
- Toggling operators works correctly, both while typing and when clicking

**Comment by zsherman** [comment]
Great, was going to suggest this. Do you have a preference? I've used a bunch (including Jest) but have also heard good things about https://github.com/avajs/ava recently.

**Comment by jsonmaur** [comment]
I do enjoy AVA and have used it in the past--but not really with React stuff. I say we give it a go and switch to Jest if it gets cumbersome.

**Comment by jsonmaur** [comment]
Done in https://github.com/timberio/react-query-assist/commit/31329d3e142eacacad1e5351727ec097e72a933a and https://github.com/timberio/react-query-assist/commit/6699c7351ea4b04f9b58a5548d8f766ffdeb1bf2.

**Comment by jsonmaur** [comment]
@zsherman Can you enable Travis builds?

**Comment by zsherman** [comment]
Yep done, here's the link https://travis-ci.org/timberio/react-query-assist.
