### ISSUE TITLE
"foo:bar:baz" is treated as valid token

### ISSUE THREAD

**Issue by jsonmaur** [timberio/react-query-assist#5]
Assuming `foo` is a valid attribute, `foo:bar` in `foo:bar:baz` is treated as a valid token. Probably shouldn't be.  See https://github.com/timberio/react-query-assist/blob/master/src/utils/token.spec.js#L25.

**Comment by jsonmaur** [comment]
@zsherman @binarylogic Is this an actual issue, or can token values be nested like this? I'm assuming enumerations will never contain colons.

**Comment by jsonmaur** [comment]
Played with the current search a bit, and seems like values can have colons such as `dt:2018-02-22T22:55:17.487Z`. So a token boundary would be from the beginning of the word to the first colon as the attribute, and everything beyond the first colon to the next space or closing quote as the value?

**Comment by zsherman** [comment]
Yeah I think that rule makes the most sense, can't think of another way to do it.

**Comment by jsonmaur** [comment]
Fixed via https://github.com/timberio/react-query-assist/commit/4fea41899aa560398a4272a49123359bb87dac62.
