### ISSUE TITLE
Better way for custom theming

### ISSUE THREAD

**Issue by jsonmaur** [timberio/react-query-assist#8]
Current implementation is a little hacky with merging custom style objects and styled-component themes. Not sure what the best way to do this is--would it make sense to implement something like https://github.com/jxnblk/styled-system?

**Comment by zsherman** [comment]
Good question, I'm a big fan of styled-system and am using it pretty heavily in react-interface. There are a few different ways I think you can go about this and tbh I haven't decided on which solution I like best yet, sometimes a combination of the two is nice.

1. Wrap it in a theme provider and look for theme attributes:

```
/* Button.js */
const Button = styled.div`
  border-color: ${props => props.theme['button.border.color']};
  border-width: ${props => props.theme['button.border.width']};
  border-style: ${props => props.theme['button.border.style']};
`
```
```
/* theme.js */
export default {
  'button.border.color': '#ddd',
  ...etc
}
```

2. Make each component a styled-component that has styled-system functions with defaults:

```
import {
  space,
  width,
  color,
  borders,
} from 'styled-system'

const Button = styled.div`
  ${space}
  ${width}
  ${color}
  ${borders}
`

Button.defaultProps = {
  bg: '#ddd',
  color: '#fff'
}
```

3. Keep doing what you're doing and let people simply specify style objects that get passed down.

**Comment by jsonmaur** [comment]
Implemented in https://github.com/timberio/react-query-assist/pull/16.
